format = "projects/v2"
id = "ea7efb89-8c2b-4008-99e2-419611fdb979"
name = "OffSec OSMR Exam Report v2.0"
language = "en-US"
tags = []
members = []
images = []
files = []

[[sections]]
id = "Student"
status = "in-progress"

[[sections]]
id = "other"
status = "in-progress"

[[sections]]
id = "highlevel_summary"
status = "in-progress"

[[sections]]
id = "appendix"
status = "in-progress"

[report_data]
title = "OffSec macOS Researcher"
firstname = "John"
lastname = "Doe"
osid = "OS-XXXXX"
mail = "student@example.com"
report_date = "2025-09-30"
report_version = "2.0"
watermark = true
highlevel_summary = "TODO A brief description of the assignments that were solved, including the overall exploitation steps."
appendix_sections = []

[[findings]]
id = "cc0cb8c0-5ee8-4fc9-b1a0-a659e31ac2fb"
order = 1

[findings.data]
title = "Assignment X"
proof = "TODO Provide the contents of local.txt, proof.txt or secret.txt."
initial_analysis = "TODO Provide relevant techniques and methods used to perform enumeration and discovery of the application and/or the environment. The steps taken should be reproducible and easy to under-stand. Include any custom code or references to public tools."
vulnerability_discovery = """
TODO Provide relevant analysis steps to locate vulnerability inside the application or environment, this includes results from static analysis and/or dynamic analysis. Explain the vulnerability identified.

Only the steps that ended up working are required.
"""
exploit_creation = "TODO Provide a description of steps to create the exploit or security control bypass. At the end of this section the full exploit (or bypass) code should be developed while an explanation of each step should be performed."
screenshots = """
TODO The exam control panel contains a section available to submit your proof files. The contents of the local.txt, proof.txt or secret.txt files obtained from your exam machines must be submitted in the control panel before your exam has ended. Note that the control panel will not indicate whether the submitted proof is correct or not. 

Each local.txt, proof.txt or secret.txt found must be shown in a screenshot that includes the con-tents of the file, as well as the IP address of the target by using ipconfig.
"""

[project_type]
file = "../offsec-designs/osmr.toml"
