format = "projects/v2"
id = "d7195b61-4c6a-4bee-ac03-7b982854343b"
name = "OffSec OSWP Exam Report v2.0"
language = "en-US"
tags = []
members = []
images = []
files = []

[[sections]]
id = "Student"
status = "in-progress"

[[sections]]
id = "other"
status = "in-progress"

[[sections]]
id = "additional"
status = "in-progress"

[[sections]]
id = "appendix"
status = "in-progress"

[report_data]
title = "OffSec Wireless Professional"
mail = "student@example.com"
osid = "OS-XXXXX"
lastname = "Doe"
firstname = "John"
report_version = "2.0"
report_date = "2025-09-30"
watermark = true
additional_items = "This section is placed for any additional items that were not mentioned in the overall report."
appendix_sections = []

[[findings]]
id = "761f283c-ad35-4b39-ae9c-3c1b51ab666c"
status = "in-progress"
order = 1


[findings.data]
title = "Access Point X"
description = "TODO A brief description of the attack chain with machine names, including the depth of compromise should be included here."
proof = "TODO Provide the contents of the \"Access Point X\" wireless network key."
steps = "TODO Provide a detailed account of your methodology in obtaining the \"Access Point X\" wireless network key. **The steps taken should be able to be easily followed and reproducible if necessary.**"
screenshots = "TODO Provide at least one screenshot of the successfully cracked \"Access Point X\" wireless network key and a screenshot of proof.txt."

[project_type]
file = "../offsec-designs/oswp.toml"
