format = "projecttypes/v2"
id = "431ca4e2-14f4-41bc-a431-07e8002b45de"
name = "OffSec OSDA Exam Report v2.0"
language = "en-US"
status = "finished"
tags = [
    "OffSec",
]
finding_ordering = []
default_notes = []
report_template = """
<div id="footer" data-sysreptor-generated="page-footer">
    <div id="footer-left"><em>CONFIDENTIAL</em></div>
    <div id="footer-center">{{ report.title }}</div>
</div>

<div v-if="report.watermark" id="watermark-osid">{{ report.osid }}</div>


<section id="page-cover" data-sysreptor-generated="page-cover">
    <img id="page-cover-logo" src="/assets/name/logo-transparent.svg" alt="logo">
    <div id="page-cover-title">
        <h1>{{ report.title }}</h1>
        <h2>Exam Report</h2>
    </div>

    <div id="page-cover-student">
        <p id="page-cover-osid">
            <strong>OSID: {{ report.osid }}</strong><br>
            {{ report.mail }}<br>
        </p>
        <p id="page-cover-meta">
            {{ formatDate(report.report_date, 'long') }}<br>
            v{{ report.report_version }}
        </p>
    </div>
</section>
<pagebreak />


<table-of-contents id="toc" v-slot="tocItems">
    <h1>Table of Contents</h1>
    <ul>
        <li v-for="item in tocItems" :class="'toc-level' + item.level">
            <ref :to="item.id" />
        </li>
    </ul>
    <pagebreak />
</table-of-contents>

<markdown>
    # OffSec Defense Analyst  Exam Report {.in-toc.numbered}
    The OffSec Defense Analyst exam report contains all efforts that were conducted in order to pass the OffSec certification examination. This report should contain all items that were used to pass the exam and it will be graded from a standpoint of correctness and fullness to all aspects of the exam. The purpose of this report is to ensure that the student has a full understanding of security detection methodologies as well as the technical knowledge to pass the qualifications for the OffSec Defense Analyst.

    ## Objective {.in-toc.numbered}
    The objective of this assessment is to perform detections and analysis on the simulated exam network in order to determine which attacker actions took place in each of the 10 phases.

    An example page has already been created for you at the latter portions of this document that should demonstrate the amount of information and detail that is expected in the exam report. Use the sample report as a guideline to get you through the reporting.

    ## Requirements {.in-toc.numbered}
    The student will be required to fill out this penetration testing report fully and to include the following sections:

    * Overall High-Level Summary of level of compromise
    * Detailed walkthrough of attacker actions in each phase
    * Each finding with included screenshots, explanations, event / log entries, and KQL queries if applicable
</markdown>
<pagebreak />

<section>
    <h1 id="summary" class="in-toc numbered">High-Level Summary</h1>
    <markdown :text="report.highlevel_summary" />
    <pagebreak />
</section>

<section>
    <h1 id="findings" class="in-toc numbered">Attacker Phases</h1>
    <div v-for="group in finding_groups">
        <h2 class="in-toc numbered">{{ group.label }}</h2>
        <div v-for="finding in group.findings">
            <h3 :id="finding.id" class="in-toc numbered">{{ finding.title }}</h3>
            <markdown :text="finding.description" />
            <pagebreak />
        </div>
    </div>
</section>

<section v-if="report.appendix_sections.length > 0" class="appendix">
    <h1 id="appendix" class="in-toc numbered">Appendix</h1>

    <div v-for="appendix_section in report.appendix_sections">
        <h2 class="in-toc numbered">{{ appendix_section.title }}</h2>
        <markdown :text="appendix_section.content" />
    </div>
    <pagebreak />
</section>

<section>
    <div class="end-of-report">
        End of Report<br>
    </div>
    <div class="end-of-report">
        This report was rendered<br>
        by <a href="https://docs.sysreptor.com/">SysReptor</a> with<br>
        <span style="color:red;">&hearts;</span><br>
    </div>
</section>
"""
report_styles = """
@import "/assets/global/base.css";

/* Define variables */
:root {
    --color-risk-critical: #E83221;
    --color-risk-high: #FF9300;
    --color-risk-medium: #FFDA00;
    --color-risk-low: #4285F5;
    --color-risk-info: #00AE51;
    
    --color-primary: #364f5b;
    --color-secondary: rgba(92, 214, 237);

    --color-table-header: var(--color-primary);
    --color-table-header-text: white;
    --color-table-row-even: rgb(221, 221, 221);
    --color-table-row-odd: white;
    --color-table-content: #151515;

    --color-code: rgb(221, 221, 221);
}

/* Font settings */
html {
    font-family: "Noto Sans", sans-serif;
    font-size: 10pt;
}


/* Global styles */
@page {
    size: A4 portrait;
    margin: 35mm 20mm 25mm 20mm;
}

a {
    font-style: italic;
    text-decoration: underline;
    color: var(--color-secondary);
}

pre code {
    border: 1px solid black;
    padding: 0.2em !important;
}
code {
    background-color: var(--color-code);
}


table {
    table-layout: fixed;
}
.markdown table {
    table-layout: auto;
}
th {
    font-weight: bold;
    background-color: var(--color-table-header);
    color: var(--color-table-header-text);
}
tr.table-row-link td {
    padding: 0;
}
tr.table-row-link td a {
    display: block;
    padding: 0.3em;
    color: inherit;
    text-decoration: none;
    font-style: inherit;
}
.table-key {
    background-color: var(--color-table-header);
    color: var(--color-table-header-text);
}
tr {
    color: var(--color-table-content);
}
tr:nth-child(even) {
    background-color: var(--color-table-row-even);
}
tr:nth-child(odd) {
    background-color: var(--color-table-row-odd);
}
tr .highlight, tr code {
    background-color: var(--color-primary);
}


/* Classes for risk colors */
.risk-critical { color: var(--color-risk-critical) !important; font-weight: bold; }
.risk-high { color: var(--color-risk-high) !important; font-weight: bold; }
.risk-medium { color: var(--color-risk-medium) !important; font-weight: bold; }
.risk-low { color: var(--color-risk-low) !important; font-weight: bold; }
.risk-info { color: var(--color-risk-info) !important; font-weight: bold; }

.risk-bg-critical { background-color: var(--color-risk-critical) !important; color: white !important; }
.risk-bg-high { background-color: var(--color-risk-high) !important; }
.risk-bg-medium { background-color: var(--color-risk-medium) !important; }
.risk-bg-low { background-color: var(--color-risk-low) !important; }
.risk-bg-info { background-color: var(--color-risk-info) !important; }

/* Helper class for referencing page number */
.ref-page::before { 
    content: "" !important;
}
.ref-page::after {
    content: target-counter(attr(href), page) !important;
}
.ref-page .ref-title {
    display: none !important;
}

/* Table in finding chapters */
.finding-heading .table-key {
    height: 3em;
    width: 10em;
}


.end-of-report {
    text-align:center;
    font-style:italic;
    margin-top:70px;
    line-height:1.7;
}





/* #region footer */
@page {
    @bottom-left { content: element(footer-left); }
    @bottom-center { content: element(footer-center); }
    @bottom-right-corner { content: counter(page); }
}
#footer {
    position: absolute;
    width: 0;
}
#footer #footer-left { position: running(footer-left); }
#footer #footer-center { position: running(footer-center); }
/* #endregion footer */

/* #region watermark */
#watermark-osid {
    position: fixed;
    top: 9cm;
    left: 1cm;
    transform: rotate(-45deg);
    font-size: 90pt;
    text-transform: uppercase;
    opacity: 0.2;
}
/* #endregion watermark */

/* #region page-cover */
#page-cover {
    page: page-cover;
}
@page page-cover {
    /* Footer on the cover page */
    @bottom-right-corner {
        content: "";
    }
    @bottom-right {
        /* Page number */
        content: counter(page);
        font-size: 9pt;
        color: white
    }
    @bottom-left {
        content: "Confidential";
        text-transform: uppercase;
        font-style: italic;
        color: white;
    }
     /* Pentest title should not appear on cover page */
    @bottom-center {
        content: '';
    }
    background-color: var(--color-primary);
}
#page-cover-logo {
    position: absolute;
    left: 2cm;
    height: 6cm;
    transform: translate(-50%, -50%);
    display: inline-block
}
/* Title page elements */
#page-cover-title {
    position: absolute;
    top: 20mm;
    left: 0;
    width: 14cm;
    color: #ffffff;
}
#page-cover-title h1 {
    font-size: 32pt;
}
#page-cover-title h2 {
    font-size: 24pt;
}
#page-cover-student {
    position: absolute;
    top: 11cm;
    left: 0;
    width: 14cm;
    color: #ffffff;
}
#page-cover-osid {
    font-size: 14pt;
}
#page-cover-meta {
    line-height: 2em;
}
/* #endregion page-cover */

/* #region toc */
#toc li {
    list-style: none;
    margin: 0;
    padding: 0;
}
#toc .ref::before {
    padding-right: 0.5em;
}
#toc .ref::after {
    content: " " leader(".") " " target-counter(attr(href), page);
}
#toc .toc-level1 {
    font-size: 1.5rem;
    font-weight: bold;
    margin-top: 0.8rem;
}
#toc .toc-level2 {
    font-size: 1.2rem;
    font-weight: bold;
    margin-top: 0.5rem;
    margin-left: 2rem;
}
#toc .toc-level3 {
    font-size: 1rem;
    margin-top: 0.4rem;
    margin-left: 4rem;
}
#toc .toc-level4 {
    font-size: 1rem;
    margin-top: 0;
    margin-left: 6rem;
}
/* #endregion toc */
"""

[[report_sections]]
id = "Student"
label = "Student"

[[report_sections.fields]]
id = "firstname"
type = "string"
label = "Firstname"
origin = "custom"
default = "John"
required = true
spellcheck = false

[[report_sections.fields]]
id = "lastname"
type = "string"
label = "Lastname"
origin = "custom"
default = "Doe"
required = true
spellcheck = false

[[report_sections.fields]]
id = "osid"
type = "string"
label = "OSID"
origin = "custom"
default = "XXXXX"
required = true
spellcheck = false

[[report_sections.fields]]
id = "mail"
type = "string"
label = "Mail"
origin = "custom"
default = "student@example.com"
required = true
spellcheck = false

[[report_sections]]
id = "other"
label = "Document Control"

[[report_sections.fields]]
id = "title"
type = "string"
label = "Title"
origin = "core"
default = "OffSec Defense Analyst"
required = true
spellcheck = true

[[report_sections.fields]]
id = "report_date"
type = "date"
label = "Report Date"
origin = "custom"
required = true

[[report_sections.fields]]
id = "report_version"
type = "string"
label = "Report Version"
origin = "custom"
default = "2.0"
required = true
spellcheck = false

[[report_sections.fields]]
id = "watermark"
type = "boolean"
label = "Watermark"
origin = "custom"
default = false

[[report_sections]]
id = "highlevel_summary"
label = "High-Level Summary"

[[report_sections.fields]]
id = "highlevel_summary"
type = "markdown"
label = "High-Level Summary"
origin = "custom"
default = """
This report details and documents the attacks observed against the OffSec OSDA exam network.

The attacker organization started by performing a brute force against an internet accessible RDP server called APPSRV02 and obtained administrative access. This led to a complete compromise of the server.

Next the attacker performed lateral movement to the internal server APPSRV02 by reusing stolen credentials from APPSRV02, this also led to a complete compromise of APPSRV03.

...
"""
required = true

[[report_sections]]
id = "appendix"
label = "Appendix"

[[report_sections.fields]]
id = "appendix_sections"
type = "list"
label = "Appendix"
origin = "custom"
required = false

[report_sections.fields.items]
id = ""
type = "object"
label = ""
origin = "custom"

[[report_sections.fields.items.properties]]
id = "title"
type = "string"
label = "Title"
origin = "custom"
default = "TODO appendix title"
required = true
spellcheck = false

[[report_sections.fields.items.properties]]
id = "content"
type = "markdown"
label = "Content"
origin = "custom"
default = "TODO appendix content"
required = true

[[finding_fields]]
id = "phase"
type = "combobox"
label = "Phase"
origin = "custom"
required = true
suggestions = [
    "Phase 1",
    "Phase 2",
]

[[finding_fields]]
id = "title"
type = "string"
label = "Action"
origin = "core"
default = "TODO Action"
required = true
spellcheck = true

[[finding_fields]]
id = "description"
type = "markdown"
label = "Detailed Description"
origin = "predefined"
default = "TODO Action Details"
required = true

[[finding_grouping]]
field = "phase"
order = "asc"

[report_preview_data.report]
title = "OffSec Defense Analyst"
firstname = "John"
lastname = "Doe"
osid = "OS-XXXXX"
mail = "student@example.com"
report_date = "2025-09-30"
report_version = "2.0"
watermark = true
highlevel_summary = """
This report details and documents the attacks observed against the OffSec OSDA exam network.

The attacker organization started by performing a brute force against an internet accessible RDP server called APPSRV02 and obtained administrative access. This led to a complete compromise of the server.

Next the attacker performed lateral movement to the internal server APPSRV02 by reusing stolen credentials from APPSRV02, this also led to a complete compromise of APPSRV03.

...
"""
appendix_sections = []

[[report_preview_data.findings]]
title = "RDP Brute Force"
description = """
The initial indicator of an attack happening was the triggering of a pre-defined threshold rule called “Possible RDP brute force” as shown below.

![RDP brute force alert](/assets/name/image-590869.png)

By looking at how the rule was defined, it is triggered by more than 100 instances of event ID 4625, which is a failed logon. This could align with a brute force attack where the attacker makes use of a user and/or password list.

When we inspect some of the events that triggered the alert, as shown below, we notice that the server reporting the events is APPSRV02.

![Failed logon events on APPSRV02](/assets/name/image-127195.png)

Given that an attacker may have attempted to brute force the server, we should search for a subsequent successful log on event to APPSRV02 to determine if they obtained access.

We do this with the following KQL query:

```
event.code:"4624" and NOT user.name:SYSTEM and NOT user.name:DWM-2
```

From this query we find the following event entry:

![Successful logon event](/assets/name/image-322213.png)

This shows that the user Peter did a successful logon to APPSRV02 shortly after the suspected brute force attack. The source IP of the logon event was 192.168.67.69 which means its not a local logon, but remotely.

At this point we have a strong suspicion that the account with the username Peter was compromised and a malicious actor obtained access to APPSRV02 coming from the IP address 192.168.67.69. We should escalate this to an incident and contact the user to verify whether this was a legitimate logon.
"""
id = "90a0038a-3649-4a37-8151-06c935a5a15e"
created = "2025-09-30T08:02:23.322362+00:00"
order = 1
phase = "Phase 1"

[[report_preview_data.findings]]
title = "Persistence"
description = """
After suspicion of a compromise, additional investigation should be performed. One area is looking for persistence and a common way attackers employ is through the registry.

To try and determine if this happed, we can use the KQL query:

```
process.name:"reg.exe"
```

As a result, we find the following event:

![Persistence via registry Run key](/assets/name/image-781171.png)

This shows that a registry change was performed. An entry for the Run key was added. The Run registry key is used when a user logs on to the computer and thus is often used for persistence.

In particular we notice that the file “C:\\Windows\\System32\\update.exe” will be executed when a user logs on to APPSRV02.

We should escalate this to investigate what the file update.exe is.
"""
id = "7b6a8c91-86d3-4764-8dcb-28dba2bae61e"
created = "2025-09-30T13:38:43.461Z"
order = 2
phase = "Phase 1"

[[report_preview_data.findings]]
title = "Summary"
description = "In this phase we have strong suspicions that a malicious actor performed a brute force attack against APPSRV02 and managed to compromise the user account with the username “Peter”. Additionally, we suspect that persistence was set up through a Run key in the registry to execute the file “C:\\Windows\\System32\\update.exe”."
id = "e902bc11-4984-4a10-bbae-c4fd89938cd7"
created = "2025-09-30T13:39:25.887Z"
order = 3
phase = "Phase 1"

[[report_preview_data.findings]]
title = "TODO Action"
description = "TODO Action Details"
id = "238d684a-8850-4a35-9f72-3abbc4d0fc2b"
created = "2025-09-30T13:40:32.935Z"
order = 4
phase = "Phase 2"

[[report_preview_data.findings]]
title = "TODO Action"
description = "TODO Action Details"
id = "fd22470a-12dc-42cf-ac02-8e84558e0fbc"
created = "2025-09-30T13:40:40.260Z"
order = 5
phase = "Phase 3"

[[report_preview_data.findings]]
title = "TODO Action"
description = "TODO Action Details"
id = "52a0d0d5-e8bd-4df2-9374-7d06f7eb2639"
created = "2025-09-30T13:40:45.134Z"
order = 6
phase = "Phase 4"

[[report_preview_data.findings]]
title = "TODO Action"
description = "TODO Action Details"
id = "0aae3a12-6672-42da-babb-987aa440cebc"
created = "2025-09-30T13:40:48.240Z"
order = 7
phase = "Phase 5"

[[report_preview_data.findings]]
title = "TODO Action"
description = "TODO Action Details"
id = "eb2c2dda-3f5e-4a73-97c6-7d357d339589"
created = "2025-09-30T13:40:51.514Z"
order = 8
phase = "Phase 6"

[[report_preview_data.findings]]
title = "TODO Action"
description = "TODO Action Details"
id = "48c4bb8b-308e-4271-829f-b1709217e511"
created = "2025-09-30T13:40:55.251Z"
order = 9
phase = "Phase 7"

[[report_preview_data.findings]]
title = "TODO Action"
description = "TODO Action Details"
id = "d99811c2-9816-47a7-8f44-e8c31092346c"
created = "2025-09-30T13:40:58.842Z"
order = 10
phase = "Phase 8"

[[report_preview_data.findings]]
title = "TODO Action"
description = "TODO Action Details"
id = "fdc3576a-9614-4f03-ba03-1bf2c3286cb3"
created = "2025-09-30T13:41:02.247Z"
order = 11
phase = "Phase 9"

[[report_preview_data.findings]]
title = "TODO Action"
description = "TODO Action Details"
id = "157a8eb4-ba59-48bd-af82-a0488c2ec4ad"
created = "2025-09-30T13:41:05.564Z"
order = 12
phase = "Phase 10"
