format = "projecttypes/v2"
id = "666aa376-9bf5-4a7a-93b0-0c1156f0beeb"
name = "OffSec OSWA Exam Report v2.0"
language = "en-US"
status = "finished"
tags = [
    "OffSec",
]
finding_ordering = []
default_notes = []
report_template = """
<div id="footer" data-sysreptor-generated="page-footer">
    <div id="footer-left"><em>CONFIDENTIAL</em></div>
    <div id="footer-center">{{ report.title }}</div>
</div>

<div v-if="report.watermark" id="watermark-osid">{{ report.osid }}</div>


<section id="page-cover" data-sysreptor-generated="page-cover">
    <img id="page-cover-logo" src="/assets/name/logo-transparent.svg" alt="logo">
    <div id="page-cover-title">
        <h1>{{ report.title }}</h1>
        <h2>Exam Report</h2>
    </div>

    <div id="page-cover-student">
        <p id="page-cover-osid">
            <strong>OSID: {{ report.osid }}</strong><br>
            {{ report.mail }}<br>
        </p>
        <p id="page-cover-meta">
            {{ formatDate(report.report_date, 'long') }}<br>
            v{{ report.report_version }}
        </p>
    </div>
</section>
<pagebreak />


<table-of-contents id="toc" v-slot="tocItems">
    <h1>Table of Contents</h1>
    <ul>
        <li v-for="item in tocItems" :class="'toc-level' + item.level">
            <ref :to="item.id" />
        </li>
    </ul>
    <pagebreak />
</table-of-contents>


<markdown>
    # OffSec Web Assessor Exam Report {.in-toc.numbered}
    The OffSec OSWA exam documentation contains all efforts that were conducted in order to pass the OffSec Web Assessor exam. This report will be graded from a standpoint of correctness and fullness to all aspects of the exam. The purpose of this report is to ensure that the student has the technical knowledge required to pass the qualifications for the OffSec Web Assessor certification.

    The student will be required to fill out this exam documentation fully and to include the following sections:
    * Methodology walkthrough and detailed outline of steps taken
    * Each finding with included screenshots, walkthrough, sample code, and proof.txt if applicable.
    * Any additional items that were not included
</markdown>
<pagebreak/>

<section>
    <div v-for="finding in findings">
        <h1 :id="finding.id" class="in-toc numbered">{{ finding.title }}</h1>
        <div v-if="finding.proof">
            <h2 class="in-toc numbered">Local.txt/Proof.txt</h2>
            <markdown :text="finding.proof" />
        </div>
        <div v-for="vulnerability in finding.vulnerabilities">
            <h2 class="in-toc numbered">{{ vulnerability.reference}}</h2>
            <markdown :text="vulnerability.details" />
        </div>
        
        <div v-if="finding.screenshots">
            <h2 class="in-toc numbered">Screenshots</h2>
            <markdown :text="finding.screenshots" />
        </div>

        <div v-if="finding.steps">
            <h2 class="in-toc numbered">Steps</h2>
            <markdown :text="finding.steps" />
        </div>
        <pagebreak />
    </div>
</section>

<section v-if="report.additional_items">
    <h1 id="additional" class="in-toc numbered">Additional Items Not Mentioned in the Report</h1>
    <markdown :text="report.additional_items" />
    <pagebreak/>
</section>

<section v-if="report.appendix_sections.length > 0" class="appendix">
    <h1 id="appendix" class="in-toc numbered">Appendix</h1>

    <div v-for="appendix_section in report.appendix_sections">
        <h2 class="in-toc numbered">{{ appendix_section.title }}</h2>
        <markdown :text="appendix_section.content" />
    </div>
    <pagebreak />
</section>

<section>
    <div class="end-of-report">
        End of Report<br>
    </div>
    <div class="end-of-report">
        This report was rendered<br>
        by <a href="https://docs.sysreptor.com/">SysReptor</a> with<br>
        <span style="color:red;">&hearts;</span><br>
    </div>
</section>
"""
report_styles = """
@import "/assets/global/base.css";

/* Define variables */
:root {
    --color-risk-critical: #E83221;
    --color-risk-high: #FF9300;
    --color-risk-medium: #FFDA00;
    --color-risk-low: #4285F5;
    --color-risk-info: #00AE51;
    
    --color-primary: #5d2c3a;
    --color-secondary: rgba(255, 69, 106);

    --color-table-header: var(--color-primary);
    --color-table-header-text: white;
    --color-table-row-even: rgb(221, 221, 221);
    --color-table-row-odd: white;
    --color-table-content: #151515;

    --color-code: rgb(221, 221, 221);
}

/* Font settings */
html {
    font-family: "Noto Sans", sans-serif;
    font-size: 10pt;
}


/* Global styles */
@page {
    size: A4 portrait;
    margin: 35mm 20mm 25mm 20mm;
}

a {
    text-decoration: underline;
    font-style: italic;
    color: var(--color-secondary);
}

pre code {
    border: 1px solid black;
    padding: 0.2em !important;
}
code {
    background-color: var(--color-code);
}


table {
    table-layout: fixed;
}
.markdown table {
    table-layout: auto;
}
th {
    font-weight: bold;
    background-color: var(--color-table-header);
    color: var(--color-table-header-text);
}
tr.table-row-link td {
    padding: 0;
}
tr.table-row-link td a {
    display: block;
    padding: 0.3em;
    color: inherit;
    text-decoration: none;
    font-style: inherit;
}
.table-key {
    background-color: var(--color-table-header);
    color: var(--color-table-header-text);
}
tr {
    color: var(--color-table-content);
}
tr:nth-child(even) {
    background-color: var(--color-table-row-even);
}
tr:nth-child(odd) {
    background-color: var(--color-table-row-odd);
}
tr .highlight, tr code {
    background-color: var(--color-primary);
}


/* Classes for risk colors */
.risk-critical { color: var(--color-risk-critical) !important; font-weight: bold; }
.risk-high { color: var(--color-risk-high) !important; font-weight: bold; }
.risk-medium { color: var(--color-risk-medium) !important; font-weight: bold; }
.risk-low { color: var(--color-risk-low) !important; font-weight: bold; }
.risk-info { color: var(--color-risk-info) !important; font-weight: bold; }

.risk-bg-critical { background-color: var(--color-risk-critical) !important; color: white !important; }
.risk-bg-high { background-color: var(--color-risk-high) !important; }
.risk-bg-medium { background-color: var(--color-risk-medium) !important; }
.risk-bg-low { background-color: var(--color-risk-low) !important; }
.risk-bg-info { background-color: var(--color-risk-info) !important; }

/* Helper class for referencing page number */
.ref-page::before { 
    content: "" !important;
}
.ref-page::after {
  content: target-counter(attr(href), page) !important;
}
.ref-page .ref-title {
  display: none !important;
}

/* Table in finding chapters */
.finding-heading .table-key {
    height: 3em;
    width: 10em;
}


.end-of-report {
    text-align:center;
    font-style:italic;
    margin-top:70px;
    line-height:1.7;
}





/* #region footer */
@page {
    @bottom-left { content: element(footer-left); }
    @bottom-center { content: element(footer-center); }
    @bottom-right-corner { content: counter(page); }
}
#footer {
    position: absolute;
    width: 0;
}
#footer #footer-left { position: running(footer-left); }
#footer #footer-center { position: running(footer-center); }
/* #endregion footer */

/* #region watermark */
#watermark-osid {
    position: fixed;
    top: 9cm;
    left: 1cm;
    transform: rotate(-45deg);
    font-size: 90pt;
    text-transform: uppercase;
    opacity: 0.2;
}
/* #endregion watermark */

/* #region page-cover */
#page-cover {
    page: page-cover;
}
@page page-cover {
    /* Footer on the cover page */
    @bottom-right-corner {
        content: "";
    }
    @bottom-right {
        /* Page number */
        content: counter(page);
        font-size: 9pt;
        color: white
    }
    @bottom-left {
        content: "Confidential";
        text-transform: uppercase;
        font-style: italic;
        color: white;
    }
     /* Pentest title should not appear on cover page */
    @bottom-center {
        content: '';
    }
    background-color: var(--color-primary);
}
#page-cover-logo {
    position: absolute;
    left: 2cm;
    height: 6cm;
    transform: translate(-50%, -50%);
    display: inline-block
}

/* Title page elements */
#page-cover-title {
    position: absolute;
    top: 20mm;
    left: 0;
    width: 14cm;
    color: #ffffff;
}
#page-cover-title h1 {
    font-size: 32pt;
}
#page-cover-title h2 {
    font-size: 24pt;
}
#page-cover-student {
    position: absolute;
    top: 11cm;
    left: 0;
    width: 14cm;
    color: #ffffff;
}
#page-cover-osid {
    font-size: 14pt;
}
#page-cover-meta {
    line-height: 2em;
}
/* #endregion page-cover */

/* #region toc */
#toc li {
    list-style: none;
    margin: 0;
    padding: 0;
}
#toc .ref::before {
    padding-right: 0.5em;
}
#toc .ref::after {
    content: " " leader(".") " " target-counter(attr(href), page);
}
#toc .toc-level1 {
    font-size: 1.5rem;
    font-weight: bold;
    margin-top: 0.8rem;
}
#toc .toc-level2 {
    font-size: 1.2rem;
    font-weight: bold;
    margin-top: 0.5rem;
    margin-left: 2rem;
}
#toc .toc-level3 {
    font-size: 1rem;
    margin-top: 0.4rem;
    margin-left: 4rem;
}
#toc .toc-level4 {
    font-size: 1rem;
    margin-top: 0;
    margin-left: 6rem;
}
/* #endregion toc */
"""

[[report_sections]]
id = "Student"
label = "Student"

[[report_sections.fields]]
id = "firstname"
type = "string"
label = "Firstname"
origin = "custom"
default = "John"
required = true
spellcheck = false

[[report_sections.fields]]
id = "lastname"
type = "string"
label = "Lastname"
origin = "custom"
default = "Doe"
required = true
spellcheck = false

[[report_sections.fields]]
id = "osid"
type = "string"
label = "OSID"
origin = "custom"
default = "XXXXX"
required = true
spellcheck = false

[[report_sections.fields]]
id = "mail"
type = "string"
label = "Mail"
origin = "custom"
default = "student@example.com"
required = true
spellcheck = false

[[report_sections]]
id = "other"
label = "Document Control"

[[report_sections.fields]]
id = "title"
type = "string"
label = "Title"
origin = "core"
default = "OffSec Web Assessor"
required = true
spellcheck = true

[[report_sections.fields]]
id = "report_date"
type = "date"
label = "Report Date"
origin = "custom"
required = true

[[report_sections.fields]]
id = "report_version"
type = "string"
label = "Report Version"
origin = "custom"
default = "2.0"
required = true
spellcheck = false

[[report_sections.fields]]
id = "watermark"
type = "boolean"
label = "Watermark"
origin = "custom"
default = false

[[report_sections]]
id = "additional"
label = "Additional Items"

[[report_sections.fields]]
id = "additional_items"
type = "markdown"
label = "Additional Items"
origin = "custom"
default = "TODO This section is placed for any additional items that were not mentioned in the overall report."
required = false

[[report_sections]]
id = "appendix"
label = "Appendix"

[[report_sections.fields]]
id = "appendix_sections"
type = "list"
label = "Appendix"
origin = "custom"
required = false

[report_sections.fields.items]
id = ""
type = "object"
label = ""
origin = "custom"

[[report_sections.fields.items.properties]]
id = "title"
type = "string"
label = "Title"
origin = "custom"
default = "TODO appendix title"
required = true
spellcheck = false

[[report_sections.fields.items.properties]]
id = "content"
type = "markdown"
label = "Content"
origin = "custom"
default = "TODO appendix content"
required = true

[[finding_fields]]
id = "title"
type = "string"
label = "Target"
origin = "core"
default = "TODO Target / IP Address"
required = true
spellcheck = true

[[finding_fields]]
id = "proof"
type = "markdown"
label = "Proof.txt"
origin = "custom"
default = "TODO Provide the contents of local.txt and proof.txt"
required = true

[[finding_fields]]
id = "vulnerabilities"
type = "list"
label = "Vulnerabilities"
origin = "custom"
required = true

[finding_fields.items]
id = ""
type = "object"
label = ""
origin = "custom"

[[finding_fields.items.properties]]
id = "reference"
type = "string"
label = "Reference"
origin = "custom"
default = "Vulnerability X"
required = true
spellcheck = false

[[finding_fields.items.properties]]
id = "details"
type = "markdown"
label = "Details"
origin = "custom"
default = "TODO Provide the method and steps used to find the vulnerability."
required = true

[[finding_fields]]
id = "screenshots"
type = "markdown"
label = "Screenshots"
origin = "custom"
default = "TODO Provide screenshots of local.txt and proof.txt contents as stated in the Exam Control Panel Objectives."
required = true

[[finding_fields]]
id = "steps"
type = "markdown"
label = "Steps"
origin = "custom"
default = "TODO Provide a detailed account of your methodology in creating the exploits. The steps taken should be able to be easily followed and reproducible if necessary."
required = true

[report_preview_data.report]
title = "OffSec Web Assessor"
firstname = "John"
lastname = "Doe"
osid = "OS-XXXXX"
mail = "student@example.com"
report_date = "2025-09-30"
report_version = "2.0"
watermark = true
additional_items = "TODO This section is placed for any additional items that were not mentioned in the overall report."
appendix_sections = []

[[report_preview_data.findings]]
title = "192.168.X.X"
id = "25a70e70-515e-4664-b7ab-dffc2f2fe12e"
created = "2025-09-30T08:02:23.143725+00:00"
order = 1
proof = "TODO Provide the contents of local.txt and proof.txt"
screenshots = "TODO Provide screenshots of local.txt and proof.txt contents as stated in the Exam Control Panel Objectives."
steps = "TODO Provide a detailed account of your methodology in creating the exploits. The steps taken should be able to be easily followed and reproducible if necessary."

[[report_preview_data.findings.vulnerabilities]]
details = "TODO Provide the method and steps used to find the vulnerability."
reference = "Vulnerability X"

[[report_preview_data.findings.vulnerabilities]]
details = "TODO Provide the method and steps used to find the vulnerability."
reference = "Vulnerability X"

[[report_preview_data.findings.vulnerabilities]]
details = "TODO Provide the method and steps used to find the vulnerability."
reference = "Vulnerability X"
