site_name: "SysReptor"
site_url: "https://docs.sysreptor.com/"
repo_url: https://github.com/syslifters/sysreptor/
site_dir: ./site/ # Where to put the HTML files
nav:
  - Features and Pricing: features-and-pricing.md
  - Setup:
      - Installation: setup/installation.md
      - Configuration: setup/configuration.md
      - Setup Webserver: setup/webserver.md
      - Updates: setup/updates.md
      - Backups: setup/backups.md
      - Upgrade to PRO: setup/upgrade-to-professional.md
  - Writing Reports:
      - Markdown Syntax: reporting/markdown-features.md
      - Version History: reporting/version-history.md
      - Spell Check: reporting/spell-check.md
      - References: reporting/references.md
      - Finding Templates: finding-templates/create-finding.md
      - Collaborative Editing: reporting/collaborative-editing.md
  - Designing Reports:
      - Designer: designer/designer.md
      - Field Types: designer/field-types.md
      - Design Guides: designer/design-guides.md
      - Page Layout: designer/page-layout.md
      - Headings and ToC: designer/headings-and-table-of-contents.md
      - Tables: designer/tables.md
      - Figures: designer/figures.md
      - Charts: designer/charts.md
      - Findings: designer/findings.md
      - Formatting Utilities: designer/formatting-utils.md
      - Debugging: designer/debugging.md
      - FAQs: designer/faqs.md
  - Finding Templates:
      - Overview: finding-templates/overview.md
      - Create Finding: finding-templates/create-finding.md
      - Multilingual: finding-templates/multilingual.md
  - Users and Permissions:
      - User Permissions: users/user-permissions.md
      - Single Sign-On:
          - SSO Setup: users/oidc-setup.md
          - Keycloak: users/oidc-keycloak.md
          - Microsoft Entra ID: users/oidc-entra-id.md
          - Google: users/oidc-google.md
          - Microsoft ADFS: users/oidc-adfs.md
          - Generic: users/oidc-generic.md
      - Forgot Password: users/forgot-password.md
      - Notifications: users/notifications.md
  - Plugins: setup/plugins.md
  - Python Integration:
      - Getting Started: python-library/index.md
      - Tutorial:
         - 1. Projects: python-library/tutorial/part-1/projects.md
         - 2. Findings: python-library/tutorial/part-2/findings.md
         - 3. Notes: python-library/tutorial/part-3/notes.md
  - Automize Reporting via CLI:
      - Getting Started: cli/getting-started.md
      - Setup: cli/setup.md
      - Configuration: cli/configuration.md
      - Tools:
          - Burp: cli/tools/burp.md
          - Nessus: cli/tools/nessus.md
          - Qualys: cli/tools/qualys.md
          - OpenVAS: cli/tools/openvas.md
          - Nmap: cli/tools/nmap.md
          - SSLyze: cli/tools/sslyze.md
          - ZAP: cli/tools/zap.md
      - Projects and Templates:
          - Project: cli/projects-and-templates/project.md
          - CreateProject: cli/projects-and-templates/createproject.md
          - PushProject: cli/projects-and-templates/pushproject.md
          - DeleteProjects: cli/projects-and-templates/deleteprojects.md
          - Finding: cli/projects-and-templates/finding.md
          - FindingFromTemplate: cli/projects-and-templates/findingfromtemplate.md
          - ExportFindings: cli/projects-and-templates/exportfindings.md
          - DeleteFindings: cli/projects-and-templates/deletefindings.md
          - Template: cli/projects-and-templates/template.md
          - File: cli/projects-and-templates/file.md
          - Note: cli/projects-and-templates/note.md
          - Translate: cli/projects-and-templates/translate.md
      - Utils:
          - Unpackarchive: cli/utils/unpackarchive.md
          - Packarchive: cli/utils/packarchive.md
      - Importers:
          - DefectDojo: cli/importers/defectdojo.md
          - Ghostwriter: cli/importers/ghostwriter.md
      - Writing plugins:
          - Tools: cli/writing-plugins/tools.md
          - Importers: cli/writing-plugins/importers.md
  - Tech Insights:
      - Architecture: insights/architecture.md
      - Show and Tell: show-and-tell/index.md
      - Rendering Workflow: insights/rendering-workflow.md
      - Archiving: insights/archiving.md
      - Security Considerations: insights/security-considerations.md
      - Vulnerabilities: insights/vulnerabilities.md
  - HTB Reporting: htb-reporting-with-sysreptor.md
  - Demo Reports: demo-reports.md
  - Contact Us: contact-us.md

theme:
  name: material
  font:
    text: Noto Sans
    code: Noto Sans
  custom_dir: overrides
  logo: images/logo.svg
  features:
    - content.code.copy
    - content.code.annotate
    - search.share
  palette:
    - scheme: default
  theme:
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/question-16

extra_css:
  - stylesheets/extra.css
  - stylesheets/hint.min.css

plugins:
  - blog:
      enabled: true
      blog_dir: show-and-tell
      archive: false
      categories: false
      post_readtime: false
  - social:
      enabled: !ENV [CI, false]
      cards: !ENV [CI, false]
      cards_layout_options:
        background_color: "#818b06"
        color: "#FFFFFF"
        font_family: "Noto Sans"
  - tooltips
  - search
  - privacy:
      enabled: !ENV [CI, false]
  - redirects:
      redirect_maps:
        "setup/nginx-server.md": "setup/webserver.md"
        "reporting/referencing-sections.md": "reporting/references.md"
        "setup/prerequisites.md": "setup/installation.md"
        "backups.md": "setup/backups.md"
        "templates.md": "finding-templates/overview.md"
        "reporting/archiving.md": "insights/archiving.md"
        "setup/user-permissions.md": "users/user-permissions.md"
        "setup/oidc-setup.md": "users/oidc-setup.md"
        "setup/oidc-keycloak.md": "users/oidc-keycloak.md"
        "setup/oidc-azure-active-directory.md": "users/oidc-entra-id.md"
        "users/oidc-azure-active-directory.md": "users/oidc-entra-id.md"
        "setup/oidc-google.md": "users/oidc-google.md"
        "setup/oidc-generic.md": "users/oidc-generic.md"
        "setup/proxy.md": "setup/configuration.md"
        "setup/network.md": "setup/configuration.md"

markdown_extensions:
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
  - pymdownx.snippets:
      url_download: true
      restrict_base_path: false
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sysreptor
    - icon: fontawesome/brands/linkedin
      link: https://at.linkedin.com/showcase/sysreptor
  generator: false

validation:
  links:
    absolute_links: relative_to_docs

copyright: '<a href="https://www.syslifters.com/" target="_blank">Our Website</a> | <a href="https://sysleaks.com/" target="_blank">SysLeaks</a> | <a href="/notice">Third Party Software</a> | <a href="https://www.syslifters.com/impressum" target="_blank">Imprint</a> | <a href="/data-privacy">Data Privacy</a> | <a href="/contact-us" target="blank">Contact</a><br><br>The FFG is the central national funding organization and strengthens Austria''s innovative power.<br>This project is funded by the <a href="https://www.ffg.at" target="_blank">FFG</a>.<br>'
